# ---------------------------------------------------------------------------- +
# p3_budman configuration settings
# ---------------------------------------------------------------------------- +

app_name = "p3_budget_manager"    # used for some defaults in places
short_app_name = "budman"         # ditto

[budman]
budget_manager_folder = "~/OneDrive/budget"   # Where data files will go
budget_manager_store = "p3_budget_manager_ca063e8b.jsonc"  # a BSM file
budget_manager_store_filetype = ".jsonc"  # a BSM filetype
budget_manager_default_workflow = "BDM_CATEGORIZATION" 
budget_manager_default_workbook_type = "WF_WORKING" 

